name: CI/CD - doc-chat

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      RENDER_DEPLOY_HOOK: ${{ secrets.RENDER_DEPLOY_HOOK }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        working-directory: backend
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install ruff pytest isort
      - name: Run isort to fix import order
        working-directory: backend
        run: isort .

      - name: Lint and auto-fix with Ruff
        working-directory: backend
        run: ruff check . --fix

      - name: Ensure no lint errors remain
        working-directory: backend
        run: ruff check .

      - name: Run API Tests
        working-directory: backend
        env:
          PYTHONPATH: .
        run: pytest tests/

      - name: Trigger Render Deployment
        run: curl -X POST $RENDER_DEPLOY_HOOK
